/**
 * BHUMI Probabilistic Risk & Tier Utility
 *
 * Implements the 5-level risk classification based on actual forecast probabilities:
 * - low (< 20%)
 * - moderate (20% - 39.9%)
 * - elevated (40% - 59.9%)
 * - high (60% - 79.9%)
 * - very high (>= 80%)
 *
 * Enforces the Stale/Experimental Data Rule:
 * Predictions generated by an unready or experimental model must never be
 * displayed as validated production forecasts.
 */

import type { LivePredictionRow } from '@/lib/supabase/types';

export type RiskLevel = 'low' | 'moderate' | 'elevated' | 'high' | 'very_high';

export interface RiskMeta {
  level: RiskLevel;
  label: string;
  rangeText: string;
  description: string;
  hexColor: string;
  badgeClass: string;
  textClass: string;
  bgClass: string;
  borderClass: string;
}

export const RISK_LEVELS: Record<RiskLevel, RiskMeta> = {
  low: {
    level: 'low',
    label: 'Low Risk',
    rangeText: '< 20%',
    description: 'Minimal atmospheric forcing; climatological baseline regime.',
    hexColor: '#10b981', // Emerald 500
    badgeClass: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/30',
    textClass: 'text-emerald-600 dark:text-emerald-400',
    bgClass: 'bg-emerald-500/10',
    borderClass: 'border-emerald-500/40',
  },
  moderate: {
    level: 'moderate',
    label: 'Moderate',
    rangeText: '20% – 39%',
    description: 'Emerging physical signal; monitor sub-seasonal evolution.',
    hexColor: '#0284c7', // Sky 600
    badgeClass: 'bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/30',
    textClass: 'text-sky-600 dark:text-sky-400',
    bgClass: 'bg-sky-500/10',
    borderClass: 'border-sky-500/40',
  },
  elevated: {
    level: 'elevated',
    label: 'Elevated',
    rangeText: '40% – 59%',
    description: 'Coherent teleconnection alignment; active farm preparedness recommended.',
    hexColor: '#f59e0b', // Amber 500
    badgeClass: 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/30',
    textClass: 'text-amber-600 dark:text-amber-400',
    bgClass: 'bg-amber-500/10',
    borderClass: 'border-amber-500/40',
  },
  high: {
    level: 'high',
    label: 'High Risk',
    rangeText: '60% – 79%',
    description: 'Strong anomalous dynamic forcing; high likelihood of event transition.',
    hexColor: '#f97316', // Orange 500
    badgeClass: 'bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-500/30',
    textClass: 'text-orange-600 dark:text-orange-400',
    bgClass: 'bg-orange-500/10',
    borderClass: 'border-orange-500/40',
  },
  very_high: {
    level: 'very_high',
    label: 'Very High Risk',
    rangeText: '≥ 80%',
    description: 'Dominant extreme regime; immediate agronomic intervention required.',
    hexColor: '#ef4444', // Red 500
    badgeClass: 'bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/30',
    textClass: 'text-red-600 dark:text-red-400',
    bgClass: 'bg-red-500/10',
    borderClass: 'border-red-500/40',
  },
};

/**
 * Returns the 5-level risk classification for a probability percentage [0.0 - 100.0].
 */
export function getRiskLevel(probability: number | null | undefined): RiskLevel {
  if (probability === null || probability === undefined || isNaN(probability)) {
    return 'low';
  }
  const p = Math.max(0, Math.min(100, probability));
  if (p < 20) return 'low';
  if (p < 40) return 'moderate';
  if (p < 60) return 'elevated';
  if (p < 80) return 'high';
  return 'very_high';
}

export function getRiskMeta(level: RiskLevel): RiskMeta {
  return RISK_LEVELS[level] || RISK_LEVELS.low;
}

export function getRiskColorHex(probability: number | null | undefined): string {
  const level = getRiskLevel(probability);
  return RISK_LEVELS[level].hexColor;
}

export function formatProbability(value: number | null | undefined): string {
  if (value === null || value === undefined || isNaN(value)) {
    return 'N/A';
  }
  return `${Math.round(value * 10) / 10}%`;
}

export interface PredictionValidationStatus {
  isValid: boolean;
  tier: 'PRODUCTION' | 'EXPERIMENTAL' | 'UNAVAILABLE';
  badgeLabel: string;
  badgeVariant: 'default' | 'secondary' | 'outline' | 'destructive';
  notice: string;
  reasons: string[];
}

/**
 * Validates prediction provenance against authoritative model readiness.
 * Prevents presenting unready or experimental model output as validated production forecasts.
 */
export function evaluatePredictionTier(
  prediction: LivePredictionRow | null | undefined,
  isModelProductionReady: boolean = false
): PredictionValidationStatus {
  if (!prediction) {
    return {
      isValid: false,
      tier: 'UNAVAILABLE',
      badgeLabel: 'No Forecast Available',
      badgeVariant: 'outline',
      notice: 'No forecast data is currently available for this location.',
      reasons: ['Prediction record missing in public.live_predictions.'],
    };
  }

  const isTaggedExperimental =
    prediction.primary_driver?.includes('[EXPERIMENTAL]') ||
    prediction.advisory_code?.startsWith('exp_') ||
    !isModelProductionReady;

  if (isTaggedExperimental) {
    return {
      isValid: true,
      tier: 'EXPERIMENTAL',
      badgeLabel: 'Experimental Outlook',
      badgeVariant: 'secondary',
      notice:
        'Experimental Model Output — Historical training coverage is currently limited. This is not a validated production forecast.',
      reasons: [
        'National 4-class multi-season validation incomplete.',
        'Historical training archive coverage is limited.',
        'Stage 1 GRU disabled pending multi-decadal sequence training.',
      ],
    };

  }

  return {
    isValid: true,
    tier: 'PRODUCTION',
    badgeLabel: 'Operational Forecast',
    badgeVariant: 'default',
    notice: 'Calibrated operational forecast validated across historical seasons.',
    reasons: [],
  };
}
